<?php
$title = 'Add model';
$this->headTitle($this->translate($title));
?>
<h1><?= $this->escapeHtml($this->translate($title)) ?></h1>
<?php
$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Username');

$fullname = $form->get('fullname');
$fullname->setAttribute('class', 'form-control');
$fullname->setAttribute('placeholder', 'Full name');

$administrator = $form->get('administrator');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($username) ?>
    <?= $this->formElement($username) ?>
    <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($fullname) ?>
    <?= $this->formElement($fullname) ?>
    <?= $this->formElementErrors()->render($fullname, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($administrator) ?>
    <?= $this->formElement($administrator) ?>
    <?= $this->formElementErrors()->render($administrator, ['class' => 'help-block']) ?>
</div>
<?
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
