<?php
$title = 'Add model';
$this->headTitle($this->translate($title));
?>
<h1><?= $this->escapeHtml($this->translate($title)) ?></h1>
<?php
$username = $form->get('name');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Name');

$fullname = $form->get('description');
$fullname->setAttribute('class', 'form-control');
$fullname->setAttribute('placeholder', 'Description');

$enabled = $form->get('enabled');

$password = $form->get('model');
$password->setAttribute('class', 'form-control');

$interface_url = $form->get('interface');
$interface_url->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');

$form->setAttribute('action', $this->url('admin/model', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($username) ?>
    <?= $this->formElement($username) ?>
    <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($fullname) ?>
    <?= $this->formElement($fullname) ?>
    <?= $this->formElementErrors()->render($fullname, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($enabled) ?>
    <?= $this->formElement($enabled) ?>
    <?= $this->formElementErrors()->render($enabled, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($interface_url) ?>
    <?= $this->formElement($interface_url) ?>
    <?= $this->formElementErrors()->render($interface_url, ['class' => 'help-block']) ?>
</div>
<?
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
